name: Dependabot auto merge

on:
  pull_request:

jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: dependabot/fetch-metadata@v2
      - if: ${{ startsWith(steps.meta.outputs.update-type, 'version-update:semver') }}
        run: |
          # gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
