name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          [[ "$HOGE" == 'hoge' ]] && echo good || echo bad
        env:
          HOGE: ${{ secrets.HOGE }}
      - run: cargo test
        env:
          GREET: ${{ secrets.GREET }}
